name: Testing Daily Docket Pull

on:
  push:
    branches: 
      - 'feature/daily-analysis-ray'

jobs:
  # Label of the container job
  daily-dockets:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `daily-dockets` executes in
    container:
      image: rayfallon/pbf-scraping:latest
    #   options: user --ci-user
    steps:
    # Downloads a copy of the code in your repository before running CI tests
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Stand up, look around
      run: |
        pwd
        whoami
        cat /etc/os-release
        python --version
        geckodriver --version
    - name: Install Project Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch and Parse Dockets
      run: |
        python analyses/full_dockets/download.py
