name: Main
on:
  schedule: 
    # Runs every day at 4am
    - cron: '0 4 * * *'

jobs:
  build:
    # Job name is Greeting
    name: Scrape and store
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Scrape data
        run: |
          make
