name: Main
on:
  workflow_dispatch:

jobs:
  build:
    # Job name is Greeting
    name: Scrape and store
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Scrape data
        run: |
          make
          ls
      - name: Parse data
        run: |
          python parse.py
          ls
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: "test-pbf-scraping"
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "output"
