name: Main

on:
  push:
    branches: 
      - 'feat-anonymize-and-switch'
  schedule: 
    # Runs every day at 4am
    - cron: '0 4 * * *'

jobs:
  build:
    # Job name is Greeting
    name: Scrape and store
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: |
          echo ::set-env name=csv_name::$(date +%Y-%m-%d -d "1 day ago").csv
          echo ::set-env name=yesterday::$(date +%Y-%m-%d -d "1 day ago").csv
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Scrape data
        run: |
          make output/"$yesterday".csv output/"$yesterday"_anonymized.csv
      - name: Parse data
        run: |
          python 1a_parse.py output/"$yesterday".csv > email_body.txt
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Bail Data
          body: file://email_body.txt
          to: ${{ secrets.LISTSERV }}
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: ./output/${{ env.yesterday }}.csv
      - name: Delete non-anonymized data
        run: |
          rm output/"$yesterday".csv
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: "pbf-new-criminal-filings"
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "output/"
