name: Main

on:
  push:
    branches: 
      - 'master'
  schedule: 
    # Runs every day at 4am
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date (e.g. 2020-01-31)'     
        required: true
      email:
        description: 'Email to'

jobs:
  build:
    # Job name is Greeting
    name: Scrape and store
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Set env
        run: |
          if [ -n "${{ github.event.inputs.date }}" ]; then
            echo '::set-env name=scrape_date::'"${{ github.event.inputs.date }}";
          else
            echo '::set-env name=scrape_date::'$(date +%Y-%m-%d -d '1 day ago');
          fi

          if [ -n "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo '::set-env name=email::'"${{ github.event.inputs.email }}";
          else
            echo '::set-env name=email::'"${{ env.LISTSERV }}"
          fi
        env:
          LISTSERV: ${{ secrets.LISTSERV }}
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Scrape data
        run: |
          make output/"$scrape_date".csv output/"$scrape_date"_anonymized.csv
      - name: Parse data
        run: |
          python 1a_parse.py output/"$scrape_date".csv > email_body.txt
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        if: ${{ env.email != "" }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Bail Data
          body: file://email_body.txt
          to: ${{ secrets.LISTSERV }}
          from: ${{ secrets.MAIL_USERNAME }}
          attachments: ./output/${{ env.scrape_date }}.csv
      - name: Delete non-anonymized data
        run: |
          rm output/"$scrape_date".csv
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: "pbf-new-criminal-filings"
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "output/"
