name: Main
on:
  workflow_dispatch:

jobs:
  build:
    # Job name is Greeting
    name: Scrape and store
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Scrape data
        run: |
          make
          csv_name=$(date +%Y-%m-%d -d "1 day ago").txt
      - name: Parse data
        run: |
          python parse.py > email_body.txt
      #- name: S3 Sync
      #  uses: jakejarvis/s3-sync-action@v0.5.1
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    AWS_S3_BUCKET: "test-pbf-scraping"
      #    AWS_REGION: "us-east-1"
      #    SOURCE_DIR: "output"
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Bail Data
          body: file://email_body.txt
          to: tuh16620@temple.edu, maryliu5758@gmail.com
          from: test.dummy.6000@gmail.com
          attachments: $csv_name
